import type { Question } from '@/domain/types';

export const ALGEBRA_QUESTIONS: Question[] = [
  // ------------------------------------------------------ Algebraic notation
  {
    id: 'alg.not.1',
    topicId: 'algebra.notation',
    grade: 2,
    kind: 'multiple-choice',
    stem: 'Simplify 5a + 3a − 2a',
    options: ['6a', '10a', '6a³', '0'],
    answerIndex: 0,
    hint: 'All the terms are "a" terms, so just combine the numbers.',
    solution: ['5 + 3 − 2 = 6', 'So 5a + 3a − 2a = 6a'],
    calculator: false,
  },
  {
    id: 'alg.not.2',
    topicId: 'algebra.notation',
    grade: 3,
    kind: 'numeric',
    stem: 'Work out the value of 3x + 7 when x = 4',
    answer: 19,
    hint: 'Replace x with 4, then follow BIDMAS.',
    solution: ['3 × 4 = 12', '12 + 7 = 19'],
    calculator: false,
  },
  {
    id: 'alg.not.3',
    topicId: 'algebra.notation',
    grade: 3,
    kind: 'multiple-choice',
    stem: 'Simplify 4x + 3y − x + 5y',
    options: ['3x + 8y', '5x + 8y', '3x + 2y', '11xy'],
    answerIndex: 0,
    hint: 'Collect the x terms and the y terms separately.',
    solution: ['4x − x = 3x', '3y + 5y = 8y', 'So the answer is 3x + 8y'],
    calculator: false,
  },
  {
    id: 'alg.not.4',
    topicId: 'algebra.notation',
    grade: 3,
    kind: 'numeric',
    stem: 'y = 5x − 3. Work out y when x = 7',
    answer: 32,
    hint: 'Multiply first, then subtract.',
    solution: ['5 × 7 = 35', '35 − 3 = 32'],
    calculator: false,
  },
  {
    id: 'alg.not.5',
    topicId: 'algebra.notation',
    grade: 4,
    kind: 'numeric',
    stem: 'Work out the value of 2p² − q when p = 3 and q = −2',
    answer: 20,
    hint: 'Square p before doubling, and remember subtracting a negative adds.',
    solution: ['p² = 3² = 9, so 2p² = 18', '18 − (−2) = 18 + 2', '= 20'],
    calculator: false,
  },
  {
    id: 'alg.not.6',
    topicId: 'algebra.notation',
    grade: 4,
    kind: 'multiple-choice',
    stem: 'Simplify 6ab ÷ 2a',
    options: ['3b', '3ab', '4b', '12b'],
    answerIndex: 0,
    hint: 'Divide the numbers, then cancel the common letter.',
    solution: ['6 ÷ 2 = 3', 'The a on the top and bottom cancel.', 'So 6ab ÷ 2a = 3b'],
    calculator: false,
  },

  // ------------------------------------------------------- Linear equations
  {
    id: 'alg.lin.1',
    topicId: 'algebra.linear-equations',
    grade: 3,
    kind: 'numeric',
    stem: 'Solve 3x + 5 = 20',
    answer: 5,
    hint: 'Subtract 5 from both sides first.',
    solution: ['3x + 5 = 20', '3x = 15', 'x = 5'],
    calculator: false,
  },
  {
    id: 'alg.lin.2',
    topicId: 'algebra.linear-equations',
    grade: 4,
    kind: 'numeric',
    stem: 'Solve 5x − 3 = 2x + 12',
    answer: 5,
    hint: 'Collect the x terms on one side and the numbers on the other.',
    solution: ['5x − 3 = 2x + 12', '3x − 3 = 12', '3x = 15', 'x = 5'],
    calculator: false,
  },
  {
    id: 'alg.lin.3',
    topicId: 'algebra.linear-equations',
    grade: 4,
    kind: 'numeric',
    stem: 'Solve 2(x + 4) = 22',
    answer: 7,
    hint: 'Divide both sides by 2, or expand the bracket first.',
    solution: ['2(x + 4) = 22', 'x + 4 = 11', 'x = 7'],
    calculator: false,
  },
  {
    id: 'alg.lin.4',
    topicId: 'algebra.linear-equations',
    grade: 5,
    kind: 'numeric',
    stem: 'Solve (x + 3)/4 = 5',
    answer: 17,
    hint: 'Multiply both sides by 4 first.',
    solution: ['(x + 3)/4 = 5', 'x + 3 = 20', 'x = 17'],
    calculator: false,
  },
  {
    id: 'alg.lin.5',
    topicId: 'algebra.linear-equations',
    grade: 5,
    kind: 'numeric',
    stem: 'Solve 3(2x − 1) = 4x + 9',
    answer: 6,
    hint: 'Expand the bracket, then collect like terms.',
    solution: ['6x − 3 = 4x + 9', '2x − 3 = 9', '2x = 12', 'x = 6'],
    calculator: false,
  },
  {
    id: 'alg.lin.6',
    topicId: 'algebra.linear-equations',
    grade: 5,
    kind: 'numeric',
    stem: 'Solve 7 − 2x = 15',
    answer: -4,
    hint: 'Watch the sign when you divide by −2.',
    solution: ['7 − 2x = 15', '−2x = 8', 'x = −4'],
    calculator: false,
  },

  // --------------------------------------------------- Expanding/factorising
  {
    id: 'alg.exp.1',
    topicId: 'algebra.expanding',
    grade: 4,
    kind: 'multiple-choice',
    stem: 'Expand 3(x + 5)',
    options: ['3x + 15', '3x + 5', 'x + 15', '3x + 8'],
    answerIndex: 0,
    hint: 'Multiply everything inside the bracket by 3.',
    solution: ['3 × x = 3x', '3 × 5 = 15', 'So 3(x + 5) = 3x + 15'],
    calculator: false,
  },
  {
    id: 'alg.exp.2',
    topicId: 'algebra.expanding',
    grade: 5,
    kind: 'multiple-choice',
    stem: 'Factorise 6x + 9 fully.',
    options: ['3(2x + 3)', '3(2x + 9)', '6(x + 3)', '3x(2 + 3)'],
    answerIndex: 0,
    hint: 'What is the highest common factor of 6 and 9?',
    solution: ['The HCF of 6 and 9 is 3.', '6x ÷ 3 = 2x and 9 ÷ 3 = 3', 'So 6x + 9 = 3(2x + 3)'],
    calculator: false,
  },
  {
    id: 'alg.exp.3',
    topicId: 'algebra.expanding',
    grade: 5,
    kind: 'multiple-choice',
    stem: 'Expand and simplify (x + 3)(x + 4)',
    options: ['x² + 7x + 12', 'x² + 12x + 7', 'x² + 7x + 7', '2x + 12'],
    answerIndex: 0,
    hint: 'Multiply every term in the first bracket by every term in the second.',
    solution: [
      'x × x = x²',
      'x × 4 = 4x and 3 × x = 3x, giving 7x',
      '3 × 4 = 12',
      'So the answer is x² + 7x + 12',
    ],
    calculator: false,
  },
  {
    id: 'alg.exp.4',
    topicId: 'algebra.expanding',
    grade: 5,
    kind: 'multiple-choice',
    stem: 'Factorise x² + 8x + 15',
    options: ['(x + 3)(x + 5)', '(x + 1)(x + 15)', '(x + 4)(x + 4)', '(x − 3)(x − 5)'],
    answerIndex: 0,
    hint: 'Find two numbers that multiply to 15 and add to 8.',
    solution: ['3 × 5 = 15 and 3 + 5 = 8', 'So x² + 8x + 15 = (x + 3)(x + 5)'],
    calculator: false,
  },
  {
    id: 'alg.exp.5',
    topicId: 'algebra.expanding',
    grade: 6,
    kind: 'multiple-choice',
    stem: 'Factorise x² − 49',
    options: ['(x + 7)(x − 7)', '(x − 7)²', '(x + 7)²', 'x(x − 49)'],
    answerIndex: 0,
    hint: 'This is a difference of two squares.',
    solution: ['49 = 7²', 'a² − b² = (a + b)(a − b)', 'So x² − 49 = (x + 7)(x − 7)'],
    calculator: false,
  },
  {
    id: 'alg.exp.6',
    topicId: 'algebra.expanding',
    grade: 6,
    kind: 'multiple-choice',
    stem: 'Expand and simplify (2x − 3)(x + 5)',
    options: ['2x² + 7x − 15', '2x² − 7x − 15', '2x² + 13x − 15', '2x² + 7x + 15'],
    answerIndex: 0,
    hint: 'Expand fully first, then collect the x terms.',
    solution: [
      '2x × x = 2x²',
      '2x × 5 = 10x and −3 × x = −3x, giving 7x',
      '−3 × 5 = −15',
      'So the answer is 2x² + 7x − 15',
    ],
    calculator: false,
  },

  // --------------------------------------------------------------- Sequences
  {
    id: 'alg.seq.1',
    topicId: 'algebra.sequences',
    grade: 4,
    kind: 'numeric',
    stem: 'What is the next term in the sequence 5, 9, 13, 17, …?',
    answer: 21,
    hint: 'Work out what is added each time.',
    solution: ['The sequence goes up by 4 each time.', '17 + 4 = 21'],
    calculator: false,
  },
  {
    id: 'alg.seq.2',
    topicId: 'algebra.sequences',
    grade: 4,
    kind: 'numeric',
    stem: 'The sequence 1, 1, 2, 3, 5, 8, … continues. What is the next term?',
    answer: 13,
    hint: 'Each term is the sum of the two before it.',
    solution: ['Each term is the sum of the previous two.', '5 + 8 = 13'],
    calculator: false,
  },
  {
    id: 'alg.seq.3',
    topicId: 'algebra.sequences',
    grade: 5,
    kind: 'multiple-choice',
    stem: 'Find the nth term of the sequence 3, 7, 11, 15, …',
    options: ['4n − 1', '4n + 3', '3n + 4', 'n + 4'],
    answerIndex: 0,
    hint: 'The common difference tells you the coefficient of n.',
    solution: [
      'The common difference is 4, so the rule starts with 4n.',
      '4 × 1 = 4, but the first term is 3, so subtract 1.',
      'The nth term is 4n − 1',
    ],
    calculator: false,
  },
  {
    id: 'alg.seq.4',
    topicId: 'algebra.sequences',
    grade: 5,
    kind: 'numeric',
    stem: 'The nth term of a sequence is 5n − 2. Work out the 10th term.',
    answer: 48,
    hint: 'Substitute n = 10.',
    solution: ['5 × 10 = 50', '50 − 2 = 48'],
    calculator: false,
  },
  {
    id: 'alg.seq.5',
    topicId: 'algebra.sequences',
    grade: 6,
    kind: 'numeric',
    stem: 'The nth term of a sequence is 4n + 2. Which term of the sequence is equal to 82?',
    answer: 20,
    hint: 'Set 4n + 2 equal to 82 and solve for n.',
    solution: ['4n + 2 = 82', '4n = 80', 'n = 20, so it is the 20th term.'],
    calculator: false,
  },
  {
    id: 'alg.seq.6',
    topicId: 'algebra.sequences',
    grade: 6,
    kind: 'multiple-choice',
    stem: 'Find the nth term of the quadratic sequence 2, 5, 10, 17, …',
    options: ['n² + 1', 'n² + n', '2n² − 1', '3n − 1'],
    answerIndex: 0,
    hint: 'Compare each term with the square numbers 1, 4, 9, 16.',
    solution: [
      'The square numbers are 1, 4, 9, 16.',
      'Each term of the sequence is one more than the matching square number.',
      'So the nth term is n² + 1',
    ],
    calculator: false,
  },
];
