import type { Question } from '@/domain/types';

export const DATA_QUESTIONS: Question[] = [
  // ------------------------------------------------------------ Probability
  {
    id: 'prob.bas.1',
    topicId: 'probability.basics',
    grade: 3,
    kind: 'numeric',
    stem: 'A fair six-sided dice is rolled. What is the probability of rolling a 4? Give your answer as a fraction or decimal.',
    answer: 1 / 6,
    tolerance: 0.002,
    hint: 'There is one favourable outcome out of six equally likely ones.',
    solution: ['There are 6 equally likely outcomes.', 'Only one of them is a 4.', 'P(4) = 1/6'],
    calculator: false,
  },
  {
    id: 'prob.bas.2',
    topicId: 'probability.basics',
    grade: 3,
    kind: 'numeric',
    stem: 'A fair six-sided dice is rolled. What is the probability of rolling an even number? Give your answer as a decimal.',
    answer: 0.5,
    tolerance: 0.002,
    hint: 'How many of 1–6 are even?',
    solution: ['The even numbers are 2, 4 and 6 — that is 3 outcomes.', 'P(even) = 3/6 = 1/2 = 0.5'],
    calculator: false,
  },
  {
    id: 'prob.bas.3',
    topicId: 'probability.basics',
    grade: 4,
    kind: 'numeric',
    stem: 'A bag holds 5 red counters and 3 blue counters. One counter is taken at random. What is the probability it is blue? Give your answer as a fraction or decimal.',
    answer: 3 / 8,
    tolerance: 0.002,
    hint: 'Count the total number of counters first.',
    solution: ['Total counters = 5 + 3 = 8', '3 of them are blue.', 'P(blue) = 3/8 = 0.375'],
    calculator: false,
  },
  {
    id: 'prob.bas.4',
    topicId: 'probability.basics',
    grade: 4,
    kind: 'numeric',
    stem: 'The probability that it rains tomorrow is 0.3. What is the probability that it does not rain?',
    answer: 0.7,
    tolerance: 0.002,
    hint: 'Probabilities of an event and its opposite add to 1.',
    solution: ['P(not rain) = 1 − P(rain)', '1 − 0.3 = 0.7'],
    calculator: false,
  },
  {
    id: 'prob.bas.5',
    topicId: 'probability.basics',
    grade: 5,
    kind: 'numeric',
    stem: 'A spinner lands on red with probability 0.2. It is spun 200 times. How many times would you expect it to land on red?',
    answer: 40,
    hint: 'Expected frequency = probability × number of trials.',
    solution: ['0.2 × 200 = 40 times'],
    calculator: true,
  },
  {
    id: 'prob.bas.6',
    topicId: 'probability.basics',
    grade: 5,
    kind: 'numeric',
    stem: 'A spinner has four colours. P(red) = 0.2, P(blue) = 0.3, P(green) = 0.15. What is P(yellow)?',
    answer: 0.35,
    tolerance: 0.002,
    hint: 'All the probabilities must add to 1.',
    solution: ['0.2 + 0.3 + 0.15 = 0.65', '1 − 0.65 = 0.35'],
    calculator: false,
  },

  // ------------------------------------------------------ Averages & range
  {
    id: 'stat.avg.1',
    topicId: 'statistics.averages',
    grade: 3,
    kind: 'numeric',
    stem: 'Work out the mean of 4, 7, 9, 12 and 13.',
    answer: 9,
    hint: 'Add them all up, then divide by how many there are.',
    solution: ['4 + 7 + 9 + 12 + 13 = 45', '45 ÷ 5 = 9'],
    calculator: false,
  },
  {
    id: 'stat.avg.2',
    topicId: 'statistics.averages',
    grade: 3,
    kind: 'numeric',
    stem: 'Work out the median of 3, 7, 2, 9 and 5.',
    answer: 5,
    hint: 'Put the numbers in order first.',
    solution: ['In order: 2, 3, 5, 7, 9', 'The middle value is 5'],
    calculator: false,
  },
  {
    id: 'stat.avg.3',
    topicId: 'statistics.averages',
    grade: 3,
    kind: 'numeric',
    stem: 'Work out the range of 12, 5, 19 and 8.',
    answer: 14,
    hint: 'Range = largest − smallest.',
    solution: ['Largest = 19, smallest = 5', '19 − 5 = 14'],
    calculator: false,
  },
  {
    id: 'stat.avg.4',
    topicId: 'statistics.averages',
    grade: 5,
    kind: 'numeric',
    stem: 'The mean of five numbers is 12. Four of them are 10, 11, 14 and 9. What is the fifth number?',
    answer: 16,
    hint: 'Work out the total of all five numbers first.',
    solution: [
      'Total of all five = 12 × 5 = 60',
      'Total of the four given = 10 + 11 + 14 + 9 = 44',
      '60 − 44 = 16',
    ],
    calculator: false,
  },
  {
    id: 'stat.avg.5',
    topicId: 'statistics.averages',
    grade: 5,
    kind: 'numeric',
    stem: 'A score of 1 occurs 3 times, a score of 2 occurs 5 times, and a score of 3 occurs 2 times. What is the mean score?',
    answer: 1.9,
    tolerance: 0.005,
    hint: 'Multiply each score by its frequency, then divide by the total frequency.',
    solution: [
      '(1 × 3) + (2 × 5) + (3 × 2) = 3 + 10 + 6 = 19',
      'Total frequency = 3 + 5 + 2 = 10',
      '19 ÷ 10 = 1.9',
    ],
    calculator: true,
  },
  {
    id: 'stat.avg.6',
    topicId: 'statistics.averages',
    grade: 6,
    kind: 'numeric',
    stem: 'The mean of 8 numbers is 15. A ninth number, 24, is added. What is the new mean?',
    answer: 16,
    hint: 'Find the original total, add 24, then divide by 9.',
    solution: [
      'Original total = 15 × 8 = 120',
      'New total = 120 + 24 = 144',
      '144 ÷ 9 = 16',
    ],
    calculator: true,
  },
];
