import type { Question } from '@/domain/types';

export const GEOMETRY_QUESTIONS: Question[] = [
  // ------------------------------------------------------------------ Ratio
  {
    id: 'rat.bas.1',
    topicId: 'ratio.basics',
    grade: 4,
    kind: 'multiple-choice',
    stem: 'Write the ratio 12 : 18 in its simplest form.',
    options: ['2 : 3', '3 : 2', '6 : 9', '1 : 2'],
    answerIndex: 0,
    hint: 'Divide both sides by their highest common factor.',
    solution: ['The HCF of 12 and 18 is 6.', '12 ÷ 6 = 2 and 18 ÷ 6 = 3', 'So 12 : 18 = 2 : 3'],
    calculator: false,
  },
  {
    id: 'rat.bas.2',
    topicId: 'ratio.basics',
    grade: 4,
    kind: 'numeric',
    stem: '£60 is shared in the ratio 2 : 3. How much is the larger share, in pounds?',
    answer: 36,
    unit: '£',
    hint: 'There are 5 parts in total.',
    solution: ['2 + 3 = 5 parts', '£60 ÷ 5 = £12 per part', '3 × £12 = £36'],
    calculator: false,
  },
  {
    id: 'rat.bas.3',
    topicId: 'ratio.basics',
    grade: 4,
    kind: 'numeric',
    stem: '45 sweets are shared between Ali and Bea in the ratio 4 : 5. How many more sweets does Bea get than Ali?',
    answer: 5,
    hint: 'Find the value of one part first.',
    solution: ['4 + 5 = 9 parts', '45 ÷ 9 = 5 sweets per part', 'The difference is 1 part = 5 sweets'],
    calculator: false,
  },
  {
    id: 'rat.bas.4',
    topicId: 'ratio.basics',
    grade: 5,
    kind: 'numeric',
    stem: 'Two numbers are in the ratio 3 : 5. The smaller number is 24. What is the total of the two numbers?',
    answer: 64,
    hint: 'Work out what one part is worth.',
    solution: ['24 ÷ 3 = 8 per part', 'Total parts = 3 + 5 = 8', '8 × 8 = 64'],
    calculator: false,
  },
  {
    id: 'rat.bas.5',
    topicId: 'ratio.basics',
    grade: 5,
    kind: 'numeric',
    stem: 'A recipe for 4 people uses 300 g of flour. How much flour is needed for 10 people, in grams?',
    answer: 750,
    unit: 'g',
    hint: 'Find the amount for one person first.',
    solution: ['300 ÷ 4 = 75 g per person', '75 × 10 = 750 g'],
    calculator: false,
  },
  {
    id: 'rat.bas.6',
    topicId: 'ratio.basics',
    grade: 6,
    kind: 'numeric',
    stem: 'a : b = 2 : 3 and b : c = 4 : 5. If c = 45, what is a?',
    answer: 24,
    hint: 'Scale both ratios so the b parts match.',
    solution: [
      'Make b the same in both: a : b = 8 : 12 and b : c = 12 : 15',
      'So a : b : c = 8 : 12 : 15',
      'c = 45 means each part is 45 ÷ 15 = 3',
      'a = 8 × 3 = 24',
    ],
    calculator: false,
  },

  // ----------------------------------------------------------------- Angles
  {
    id: 'geo.ang.1',
    topicId: 'geometry.angles',
    grade: 3,
    kind: 'numeric',
    stem: 'Two angles sit on a straight line. One is 115°. What is the other, in degrees?',
    answer: 65,
    unit: '°',
    hint: 'Angles on a straight line add to 180°.',
    solution: ['Angles on a straight line add up to 180°.', '180 − 115 = 65°'],
    calculator: false,
  },
  {
    id: 'geo.ang.2',
    topicId: 'geometry.angles',
    grade: 4,
    kind: 'numeric',
    stem: 'A triangle has angles of 47° and 68°. What is the third angle, in degrees?',
    answer: 65,
    unit: '°',
    hint: 'Angles in a triangle add to 180°.',
    solution: ['47 + 68 = 115', '180 − 115 = 65°'],
    calculator: false,
  },
  {
    id: 'geo.ang.3',
    topicId: 'geometry.angles',
    grade: 4,
    kind: 'multiple-choice',
    stem: 'Two parallel lines are crossed by a straight line. Co-interior (allied) angles add up to what?',
    options: ['180°', '90°', '360°', 'They are equal'],
    answerIndex: 0,
    hint: 'Co-interior angles form a "C" shape between the parallel lines.',
    solution: ['Co-interior angles lie between the parallel lines on the same side.', 'They are supplementary, so they add to 180°.'],
    calculator: false,
  },
  {
    id: 'geo.ang.4',
    topicId: 'geometry.angles',
    grade: 4,
    kind: 'numeric',
    stem: 'What is the sum of the interior angles of a hexagon, in degrees?',
    answer: 720,
    unit: '°',
    hint: 'Use (n − 2) × 180 with n = 6.',
    solution: ['A hexagon has 6 sides.', '(6 − 2) × 180 = 4 × 180', '= 720°'],
    calculator: false,
  },
  {
    id: 'geo.ang.5',
    topicId: 'geometry.angles',
    grade: 5,
    kind: 'numeric',
    stem: 'What is the size of each exterior angle of a regular decagon, in degrees?',
    answer: 36,
    unit: '°',
    hint: 'Exterior angles of any polygon add to 360°.',
    solution: ['A decagon has 10 sides.', '360 ÷ 10 = 36°'],
    calculator: false,
  },
  {
    id: 'geo.ang.6',
    topicId: 'geometry.angles',
    grade: 5,
    kind: 'numeric',
    stem: 'Each interior angle of a regular polygon is 156°. How many sides does it have?',
    answer: 15,
    hint: 'Find the exterior angle first.',
    solution: [
      'Exterior angle = 180 − 156 = 24°',
      'Number of sides = 360 ÷ 24',
      '= 15 sides',
    ],
    calculator: false,
  },

  // ------------------------------------------------------ Area and perimeter
  {
    id: 'geo.area.1',
    topicId: 'geometry.area-perimeter',
    grade: 3,
    kind: 'numeric',
    stem: 'A rectangle is 8 cm long and 5 cm wide. What is its area, in cm²?',
    answer: 40,
    unit: 'cm²',
    hint: 'Area of a rectangle = length × width.',
    solution: ['8 × 5 = 40 cm²'],
    calculator: false,
  },
  {
    id: 'geo.area.2',
    topicId: 'geometry.area-perimeter',
    grade: 4,
    kind: 'numeric',
    stem: 'A triangle has base 12 cm and perpendicular height 7 cm. What is its area, in cm²?',
    answer: 42,
    unit: 'cm²',
    hint: 'Area of a triangle = ½ × base × height.',
    solution: ['12 × 7 = 84', '84 ÷ 2 = 42 cm²'],
    calculator: false,
  },
  {
    id: 'geo.area.3',
    topicId: 'geometry.area-perimeter',
    grade: 5,
    kind: 'numeric',
    stem: 'A circle has radius 5 cm. What is its area in cm², to 1 decimal place?',
    answer: 78.5,
    tolerance: 0.15,
    unit: 'cm²',
    hint: 'Area of a circle = πr².',
    solution: ['Area = π × 5² = 25π', '25 × 3.14159… = 78.5 cm² (1 d.p.)'],
    calculator: true,
  },
  {
    id: 'geo.area.4',
    topicId: 'geometry.area-perimeter',
    grade: 5,
    kind: 'numeric',
    stem: 'A circle has diameter 14 cm. What is its circumference in cm, to 1 decimal place?',
    answer: 44,
    tolerance: 0.15,
    unit: 'cm',
    hint: 'Circumference = π × diameter.',
    solution: ['C = π × 14', '= 43.98… ≈ 44.0 cm (1 d.p.)'],
    calculator: true,
  },
  {
    id: 'geo.area.5',
    topicId: 'geometry.area-perimeter',
    grade: 5,
    kind: 'numeric',
    stem: 'A trapezium has parallel sides 6 cm and 10 cm, and height 4 cm. What is its area, in cm²?',
    answer: 32,
    unit: 'cm²',
    hint: 'Area = ½ × (a + b) × h.',
    solution: ['(6 + 10) ÷ 2 = 8', '8 × 4 = 32 cm²'],
    calculator: false,
  },
  {
    id: 'geo.area.6',
    topicId: 'geometry.area-perimeter',
    grade: 6,
    kind: 'numeric',
    stem: 'A sector of a circle has radius 9 cm and angle 40°. What is its area in cm², to 1 decimal place?',
    answer: 28.3,
    tolerance: 0.2,
    unit: 'cm²',
    hint: 'The sector is 40/360 of the whole circle.',
    solution: [
      'Full circle area = π × 9² = 81π',
      'Sector = (40/360) × 81π = 9π',
      '9 × 3.14159… = 28.3 cm² (1 d.p.)',
    ],
    calculator: true,
  },

  // ------------------------------------------------------------- Pythagoras
  {
    id: 'geo.pyth.0',
    topicId: 'geometry.pythagoras',
    grade: 4,
    kind: 'multiple-choice',
    stem: 'In a right-angled triangle, which side is the hypotenuse?',
    options: [
      'The side opposite the right angle',
      'The shortest side',
      'The horizontal side',
      'The side next to the right angle',
    ],
    answerIndex: 0,
    hint: 'It is always the longest side.',
    solution: [
      'The hypotenuse is the side opposite the right angle.',
      'It is always the longest side of a right-angled triangle.',
    ],
    calculator: false,
  },
  {
    id: 'geo.pyth.1',
    topicId: 'geometry.pythagoras',
    grade: 5,
    kind: 'numeric',
    stem: 'A right-angled triangle has shorter sides 6 cm and 8 cm. What is the length of the hypotenuse, in cm?',
    answer: 10,
    unit: 'cm',
    hint: 'a² + b² = c².',
    solution: ['6² + 8² = 36 + 64 = 100', '√100 = 10 cm'],
    calculator: true,
  },
  {
    id: 'geo.pyth.2',
    topicId: 'geometry.pythagoras',
    grade: 5,
    kind: 'numeric',
    stem: 'A right-angled triangle has shorter sides 5 cm and 12 cm. What is the length of the hypotenuse, in cm?',
    answer: 13,
    unit: 'cm',
    hint: 'a² + b² = c².',
    solution: ['5² + 12² = 25 + 144 = 169', '√169 = 13 cm'],
    calculator: true,
  },
  {
    id: 'geo.pyth.3',
    topicId: 'geometry.pythagoras',
    grade: 5,
    kind: 'numeric',
    stem: 'A right-angled triangle has hypotenuse 17 cm and one shorter side 8 cm. What is the other shorter side, in cm?',
    answer: 15,
    unit: 'cm',
    hint: 'To find a shorter side you subtract, not add.',
    solution: ['17² − 8² = 289 − 64 = 225', '√225 = 15 cm'],
    calculator: true,
  },
  {
    id: 'geo.pyth.4',
    topicId: 'geometry.pythagoras',
    grade: 6,
    kind: 'numeric',
    stem: 'A right-angled triangle has shorter sides 7 cm and 9 cm. What is the hypotenuse in cm, to 2 decimal places?',
    answer: 11.4,
    tolerance: 0.02,
    unit: 'cm',
    hint: 'Add the squares, then square root.',
    solution: ['7² + 9² = 49 + 81 = 130', '√130 = 11.40 cm (2 d.p.)'],
    calculator: true,
  },
  {
    id: 'geo.pyth.5',
    topicId: 'geometry.pythagoras',
    grade: 6,
    kind: 'numeric',
    stem: 'A square has side 6 cm. What is the length of its diagonal in cm, to 2 decimal places?',
    answer: 8.49,
    tolerance: 0.02,
    unit: 'cm',
    hint: 'The diagonal splits the square into two right-angled triangles.',
    solution: ['6² + 6² = 36 + 36 = 72', '√72 = 8.49 cm (2 d.p.)'],
    calculator: true,
  },
  {
    id: 'geo.pyth.6',
    topicId: 'geometry.pythagoras',
    grade: 6,
    kind: 'numeric',
    stem: 'What is the distance between the points (1, 2) and (5, 7), to 2 decimal places?',
    answer: 6.4,
    tolerance: 0.02,
    hint: 'Find the horizontal and vertical gaps, then use Pythagoras.',
    solution: [
      'Horizontal difference = 5 − 1 = 4',
      'Vertical difference = 7 − 2 = 5',
      '4² + 5² = 16 + 25 = 41',
      '√41 = 6.40 (2 d.p.)',
    ],
    calculator: true,
  },
  {
    id: 'geo.pyth.7',
    topicId: 'geometry.pythagoras',
    grade: 7,
    kind: 'numeric',
    stem: 'A cuboid measures 3 cm by 4 cm by 12 cm. What is the length of the longest diagonal inside it, in cm?',
    answer: 13,
    unit: 'cm',
    hint: 'Use Pythagoras twice: first across the base, then up to the far corner.',
    solution: [
      'Base diagonal: 3² + 4² = 9 + 16 = 25, so the base diagonal is 5 cm.',
      'Now use that with the height: 5² + 12² = 25 + 144 = 169',
      '√169 = 13 cm',
    ],
    calculator: true,
  },
];
