import type { Question } from '@/domain/types';

/**
 * Number strand questions.
 *
 * Each question is authored with the GCSE grade it would typically appear at; that grade
 * is the difficulty the adaptive engine selects against, so a topic needs questions
 * spread across a band of grades to be useful.
 */
export const NUMBER_QUESTIONS: Question[] = [
  // ------------------------------------------------ Integers & place value
  {
    id: 'num.int.1',
    topicId: 'number.integers',
    grade: 2,
    kind: 'multiple-choice',
    stem: 'Work out −7 + 12',
    options: ['5', '−5', '19', '−19'],
    answerIndex: 0,
    hint: 'Start at −7 on a number line and count 12 to the right.',
    solution: ['−7 + 12 means moving 12 to the right from −7.', '−7 + 12 = 5'],
    calculator: false,
  },
  {
    id: 'num.int.2',
    topicId: 'number.integers',
    grade: 3,
    kind: 'numeric',
    stem: 'Work out −6 × −4',
    answer: 24,
    hint: 'A negative multiplied by a negative gives a positive.',
    solution: ['6 × 4 = 24', 'Two negatives multiplied give a positive, so −6 × −4 = 24'],
    calculator: false,
  },
  {
    id: 'num.int.3',
    topicId: 'number.integers',
    grade: 2,
    kind: 'numeric',
    stem: 'Round 3847 to the nearest 100.',
    answer: 3800,
    hint: 'Look at the tens digit to decide which way to round.',
    solution: [
      'The hundreds digit is 8, and the tens digit is 4.',
      '4 is less than 5, so round down.',
      '3847 rounds to 3800',
    ],
    calculator: false,
  },
  {
    id: 'num.int.4',
    topicId: 'number.integers',
    grade: 3,
    kind: 'multiple-choice',
    stem: 'Which of these numbers is the largest?',
    options: ['−12', '−3', '0.5', '−0.2'],
    answerIndex: 2,
    hint: 'Any positive number is larger than every negative number.',
    solution: [
      'Only 0.5 is positive.',
      'A positive number is always greater than a negative one, so 0.5 is largest.',
    ],
    calculator: false,
  },
  {
    id: 'num.int.5',
    topicId: 'number.integers',
    grade: 4,
    kind: 'numeric',
    stem: 'Work out (−3)² − 4 × (−2)',
    answer: 17,
    hint: 'Follow BIDMAS: indices first, then multiplication, then subtraction.',
    solution: [
      '(−3)² = 9',
      '4 × (−2) = −8',
      '9 − (−8) = 9 + 8 = 17',
    ],
    calculator: false,
  },
  {
    id: 'num.int.6',
    topicId: 'number.integers',
    grade: 4,
    kind: 'numeric',
    stem: 'At midnight the temperature was −8 °C. By noon it was 5 °C. By how many degrees did the temperature rise?',
    answer: 13,
    unit: '°C',
    hint: 'Count from −8 up to 0, then from 0 up to 5.',
    solution: ['From −8 to 0 is 8 degrees.', 'From 0 to 5 is 5 degrees.', '8 + 5 = 13 °C'],
    calculator: false,
  },

  // ------------------------------------------------------------- Fractions
  {
    id: 'num.frac.1',
    topicId: 'number.fractions',
    grade: 3,
    kind: 'multiple-choice',
    stem: 'Simplify 18/24 fully.',
    options: ['3/4', '9/12', '6/8', '2/3'],
    answerIndex: 0,
    hint: 'Find the highest common factor of 18 and 24.',
    solution: ['The HCF of 18 and 24 is 6.', '18 ÷ 6 = 3 and 24 ÷ 6 = 4', 'So 18/24 = 3/4'],
    calculator: false,
  },
  {
    id: 'num.frac.2',
    topicId: 'number.fractions',
    grade: 4,
    kind: 'numeric',
    stem: 'Work out 2/5 of 350',
    answer: 140,
    hint: 'Divide by the denominator first, then multiply by the numerator.',
    solution: ['350 ÷ 5 = 70', '70 × 2 = 140'],
    calculator: false,
  },
  {
    id: 'num.frac.3',
    topicId: 'number.fractions',
    grade: 4,
    kind: 'numeric',
    stem: 'Work out 3/4 + 1/6. Give your answer as a fraction.',
    answer: 11 / 12,
    tolerance: 0.001,
    hint: 'Use a common denominator of 12.',
    solution: ['3/4 = 9/12 and 1/6 = 2/12', '9/12 + 2/12 = 11/12'],
    calculator: false,
  },
  {
    id: 'num.frac.4',
    topicId: 'number.fractions',
    grade: 5,
    kind: 'numeric',
    stem: 'Work out 2 1/2 ÷ 3/4. Give your answer as a fraction or decimal.',
    answer: 10 / 3,
    tolerance: 0.005,
    hint: 'Convert to an improper fraction, then multiply by the reciprocal.',
    solution: [
      '2 1/2 = 5/2',
      'Dividing by 3/4 is the same as multiplying by 4/3.',
      '5/2 × 4/3 = 20/6 = 10/3 = 3 1/3',
    ],
    calculator: false,
  },
  {
    id: 'num.frac.5',
    topicId: 'number.fractions',
    grade: 5,
    kind: 'multiple-choice',
    stem: 'Write 0.375 as a fraction in its simplest form.',
    options: ['3/8', '375/100', '3/4', '5/8'],
    answerIndex: 0,
    hint: '0.375 is 375 thousandths.',
    solution: ['0.375 = 375/1000', 'Divide top and bottom by 125.', '375/1000 = 3/8'],
    calculator: false,
  },
  {
    id: 'num.frac.6',
    topicId: 'number.fractions',
    grade: 6,
    kind: 'numeric',
    stem: 'Write the recurring decimal 0.4444… as a fraction.',
    answer: 4 / 9,
    tolerance: 0.002,
    hint: 'Let x = 0.444…, then consider 10x − x.',
    solution: [
      'Let x = 0.444…, so 10x = 4.444…',
      '10x − x = 4.444… − 0.444… = 4',
      '9x = 4, so x = 4/9',
    ],
    calculator: false,
  },

  // ----------------------------------------------------------- Percentages
  {
    id: 'num.pct.1',
    topicId: 'number.percentages',
    grade: 4,
    kind: 'numeric',
    stem: 'Work out 15% of 240',
    answer: 36,
    hint: '10% is 24, and 5% is half of that.',
    solution: ['10% of 240 = 24', '5% of 240 = 12', '15% = 24 + 12 = 36'],
    calculator: false,
  },
  {
    id: 'num.pct.2',
    topicId: 'number.percentages',
    grade: 4,
    kind: 'numeric',
    stem: 'Increase 80 by 20%.',
    answer: 96,
    hint: 'Multiply by 1.2.',
    solution: ['20% of 80 = 16', '80 + 16 = 96', 'Or directly: 80 × 1.2 = 96'],
    calculator: false,
  },
  {
    id: 'num.pct.3',
    topicId: 'number.percentages',
    grade: 5,
    kind: 'numeric',
    stem: 'Write 36 out of 48 as a percentage.',
    answer: 75,
    unit: '%',
    hint: 'Divide, then multiply by 100.',
    solution: ['36 ÷ 48 = 0.75', '0.75 × 100 = 75%'],
    calculator: true,
  },
  {
    id: 'num.pct.4',
    topicId: 'number.percentages',
    grade: 5,
    kind: 'multiple-choice',
    stem: 'Which multiplier decreases an amount by 12%?',
    options: ['0.88', '1.12', '0.12', '0.98'],
    answerIndex: 0,
    hint: 'After a 12% decrease, what percentage is left?',
    solution: ['100% − 12% = 88%', '88% as a decimal is 0.88'],
    calculator: false,
  },
  {
    id: 'num.pct.5',
    topicId: 'number.percentages',
    grade: 6,
    kind: 'numeric',
    stem: 'In a sale, a jacket is reduced by 25% to £45. What was the original price in pounds?',
    answer: 60,
    unit: '£',
    hint: '£45 represents 75% of the original price.',
    solution: [
      'After a 25% reduction, £45 is 75% of the original.',
      'Original = 45 ÷ 0.75',
      'Original = £60',
    ],
    calculator: true,
  },
  {
    id: 'num.pct.6',
    topicId: 'number.percentages',
    grade: 6,
    kind: 'numeric',
    stem: 'A house is worth £250 000. Its value rises by 4% each year. What is it worth after 2 years?',
    answer: 270400,
    unit: '£',
    hint: 'Multiply by 1.04 twice.',
    solution: [
      'Multiplier for a 4% increase is 1.04',
      '250000 × 1.04² = 250000 × 1.0816',
      '= £270 400',
    ],
    calculator: true,
  },

  // ------------------------------------------------------- Indices & roots
  {
    id: 'num.ind.1',
    topicId: 'number.indices',
    grade: 4,
    kind: 'numeric',
    stem: 'Work out 2⁵',
    answer: 32,
    hint: 'Multiply 2 by itself five times.',
    solution: ['2 × 2 × 2 × 2 × 2', '= 32'],
    calculator: false,
  },
  {
    id: 'num.ind.2',
    topicId: 'number.indices',
    grade: 5,
    kind: 'multiple-choice',
    stem: 'Simplify x⁷ ÷ x³',
    options: ['x⁴', 'x¹⁰', 'x²¹', 'x'],
    answerIndex: 0,
    hint: 'When dividing powers of the same base, subtract the indices.',
    solution: ['x⁷ ÷ x³ = x⁷⁻³', '= x⁴'],
    calculator: false,
  },
  {
    id: 'num.ind.3',
    topicId: 'number.indices',
    grade: 5,
    kind: 'numeric',
    stem: 'Work out (2³)²',
    answer: 64,
    hint: 'When raising a power to a power, multiply the indices.',
    solution: ['(2³)² = 2⁶', '2⁶ = 64'],
    calculator: false,
  },
  {
    id: 'num.ind.4',
    topicId: 'number.indices',
    grade: 6,
    kind: 'multiple-choice',
    stem: 'What is the value of 5⁻²?',
    options: ['1/25', '−25', '−10', '25'],
    answerIndex: 0,
    hint: 'A negative index means the reciprocal.',
    solution: ['5⁻² = 1/5²', '= 1/25'],
    calculator: false,
  },
  {
    id: 'num.ind.5',
    topicId: 'number.indices',
    grade: 7,
    kind: 'numeric',
    stem: 'Work out 27^(2/3)',
    answer: 9,
    hint: 'The denominator is a root, the numerator is a power.',
    solution: ['The cube root of 27 is 3.', '3² = 9'],
    calculator: false,
  },
  {
    id: 'num.ind.6',
    topicId: 'number.indices',
    grade: 7,
    kind: 'numeric',
    stem: 'Work out 8^(−2/3). Give your answer as a decimal.',
    answer: 0.25,
    tolerance: 0.001,
    hint: 'Deal with the negative index first, then the fractional index.',
    solution: [
      '8^(−2/3) = 1 / 8^(2/3)',
      'The cube root of 8 is 2, and 2² = 4',
      'So the answer is 1/4 = 0.25',
    ],
    calculator: false,
  },
];
